
--Q1. What is the total revenue generated by male vs. female customers?
select "Gender", SUM("Purchase Amount (USD)") 
as revenue
from customer
group by "Gender";

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select "Customer ID", "Purchase Amount (USD)" as spent 
from customer 
where "Discount Applied" = 'Yes' and "Purchase Amount (USD)" >= (select AVG("Purchase Amount (USD)") from customer);

--Q3. Which are the top 5 products with the highest average review rating?
select "Item Purchased", round(avg("Review Rating")::numeric, 2)
as "Average Product Rating" 
from customer 
group by "Item Purchased"
order by "Average Product Rating" DESC
LIMIT 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping?
select "Shipping Type",
        round(avg("Purchase Amount (USD)")::numeric, 2)
		as "Average Purchase Amount"
		from customer
		where "Shipping Type" in ('Standard', 'Express')
		group by "Shipping Type";

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select "Subscription Status", count("Customer ID")
as total_customers,
round(avg("Purchase Amount (USD)")::NUMERIC, 2)
as avg_spend, SUM("Purchase Amount (USD)")as total_revenue
from customer
group by "Subscription Status"
order by total_revenue DESC, avg_spend
DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT "Item Purchased",
       ROUND((100.0 * SUM(CASE WHEN "Discount Applied" = 'Yes' THEN 1 ELSE 0 END)/COUNT(*))::numeric, 2) AS "Discount Rate"
FROM customer
GROUP BY "Item Purchased"
ORDER BY "Discount Rate" DESC
LIMIT 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with "Customer_Type" as (
SELECT "Customer ID" , "Previous Purchases",
CASE 
    WHEN "Previous Purchases" = 1 THEN 'New'
    WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS "Customer Segment"
FROM customer)

select "Customer Segment",count(*) AS "Number of Customers" 
from "Customer_Type" 
group by "Customer Segment";

--Q8. What are the top 3 most purchased products within each category? 
WITH "Item Counts" AS (
    SELECT "Category",
           "Item Purchased",
           COUNT("Customer ID") AS "Total Orders",
           ROW_NUMBER() OVER (PARTITION BY "Category" ORDER BY COUNT("Customer ID") DESC) AS "Item Rank"
    FROM customer
    GROUP BY "Category", "Item Purchased"
)
SELECT "Item Rank","Category", "Item Purchased", "Total Orders"
FROM "Item Counts"
WHERE "Item Rank" <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT "Subscription Status",
       COUNT("Customer ID") AS "Repeat Buyers"
FROM customer
WHERE "Previous Purchases" > 5
GROUP BY "Subscription Status";

--Q10. What is the revenue contribution of each age group? 
SELECT 
     CASE
    WHEN "Age" < 30 THEN 'Young Adult'
	WHEN "Age" BETWEEN 30 AND 50
	THEN 'Middle-Aged'
	ELSE 'Senior'
	END AS "Age Group",
    SUM("Purchase Amount (USD)") AS "Total Revenue"
FROM customer
GROUP BY "Age Group"
ORDER BY "Total Revenue" desc;
